services:
  - type: web
    name: smartvision-backend
    env: python
    plan: free
    autoDeploy: true

    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    workingDirectory: backend
